services:
  api:
    privileged: ${DOCKER_GIT_CONTROLLER_PRIVILEGED:-true}
    environment:
      DOCKER_GIT_PROJECT_DOCKER_HOST: ${DOCKER_GIT_PROJECT_DOCKER_HOST:-tcp://host.docker.internal:2375}
    volumes: !override
      - docker_git_projects:${DOCKER_GIT_PROJECTS_ROOT:-/home/dev/.docker-git}
      - docker_git_docker_data:/var/lib/docker
